# Database settings.
database:

  # the name of your JDBC driver
  driverClass: org.postgresql.Driver

  # the username
  user: root

  # the password
  password: root

  # the JDBC URL
  url: jdbc:postgresql://localhost:5432/test_db

  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect